graph TD
  dashboard       --> ecs
  dashboard       --> rds
  resource-groups --> bastion
  resource-groups --> ecr
  resource-groups --> ecs
  resource-groups --> network
  resource-groups --> rds
  rds             --> network
  bastion         --> network
  bastion         --> rds
  ecs             --> network
  ecs             --> rds
  ecs             --> ecr
  common          --> resource-groups
  common          --> rds
  common          --> ecs


