#!/usr/bin/env bash

BOOTSTRAP_DIR=$(pwd)/../bootstrap

pushd $BOOTSTRAP_DIR > /dev/null
STATE_BUCKET=$(terraform output state_bucket)
DYNAMODB_TABLE=$(terraform output dynamodb_table)
KMS_KEY_ID=$(terraform output kms_key_id)
popd > /dev/null

terraform init \
          -backend-config="bucket=$STATE_BUCKET" \
          -backend-config="dynamodb_table=$DYNAMODB_TABLE" \
          -backend-config="kms_key_id=$KMS_KEY_ID"
